name: Deploy Docs
on:
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache

      - run: pip install mkdocs-material
      - run: python -m -c "import sys; print(sys.path)"
      - run: python -m -c "import docs.extensions.func_args"
      - run: python -m mkdocs gh-deploy --force --verbose
